### PR TITLE
July 2020 review

### LINKED ISSUE #10: July 2020 review
Issues found during review:

- Semantics of many elements can be improved.
- GeoReferenceVariant does not have alternatives for Circle or Path, even though the discriminant Enum type does (which is not used for anything else). **EDIT:** Suggest adding alternative for Circle with data type GeodeticCircle.
- NETNGeoObjectReference of GeoReferenceVariant should refer to Point, Path or Area. (Not to “leaf classes”, as that excludes area and includes volume instead.)
- SeaStateEnum16 values have wrong naming convention. Should use CamelCase instead of Upper_snake_case.
- Inconsistent naming and typing of Enum types. Should Enum type names include bit size? Should we, in general, use 16 or 32 bits for enums? **EDIT:** Enum type names should indeed include bit size. Suggest correcting the names, but not changing bit size of any types now.
- IceTypeEnum has only one value: 0 (None).
- ~~Swell and Wave attributes of WaterSurface have identical data types and semantics. Should probably remove Swell.~~

### PR DESCRIPTION
**Pull request by linusonline**

### CODE REVIEW

**Comment by lofstrandbjorn** [comment]
In ObjectClass Weather semantics:

"An instance of this class without a GeoReference is considered global above sea level." is not correct.

Should be "An instance of this class without a GeoReference is considered global."


E.g. there might be a global subsurface condition (same salinity in all bodies of water).

**Comment by lofstrandbjorn** [comment]
milibar  -> millibar

**Comment by lofstrandbjorn** [comment]
Can currents , waves and swell exists even if there is 100% ice? Perhaps remove the statement on N/A since the attributes are optional anyway.

**Comment by linusonline** [comment]
@lofstrandbjorn 

> In ObjectClass Weather semantics:
> 
> "An instance of this class without a GeoReference is considered global above sea level." is not correct.
> 
> Should be "An instance of this class without a GeoReference is considered global."
> 
> E.g. there might be a global subsurface condition (same salinity in all bodies of water).

But SubsurfaceLayer does not inherit from the Weather class.

The intention of that sentence was to refer to instance of Weather specifically, not its subclasses. I could clarify that, but not sure how to rephrase it.

So, given that, the Weather semantics should be correct, no?

**Comment by lofstrandbjorn** [comment]
Subsurface Layer. Should the base be the bottom or top of the layer? I.e. base + depth or base + height.?

**Comment by linusonline** [comment]
> Can currents , waves and swell exists even if there is 100% ice? Perhaps remove the statement on N/A since the attributes are optional anyway.

I did remove it from the Wave attribute. I didn't change the Swell attribute at all, because, as stated in #10 , I expect it to be removed entirely.

**Comment by linusonline** [comment]
> Subsurface Layer. Should the base be the bottom or top of the layer? I.e. base + depth or base + height.?

SubsurfaceLayer->Layer: "A body of water extending from a (negative) base altitude upwards (see LayerStruct)."
LayerStruct->Thickness: "Thickness of the layer in meters above the base altitude. Always a positive value."

Is this unclear?

**Comment by lofstrandbjorn** [comment]
> @lofstrandbjorn
> 
> > In ObjectClass Weather semantics:
> > "An instance of this class without a GeoReference is considered global above sea level." is not correct.
> > Should be "An instance of this class without a GeoReference is considered global."
> > E.g. there might be a global subsurface condition (same salinity in all bodies of water).
> 
> But SubsurfaceLayer does not inherit from the Weather class.
> 
> The intention of that sentence was to refer to instance of Weather specifically, not its subclasses. I could clarify that, but not sure how to rephrase it.
> 
> So, given that, the Weather semantics should be correct, no?

Yes. Agree. Correct.

**Comment by lofstrandbjorn** [comment]
> > Subsurface Layer. Should the base be the bottom or top of the layer? I.e. base + depth or base + height.?
> 
> SubsurfaceLayer->Layer: "A body of water extending from a (negative) base altitude upwards (see LayerStruct)."
> LayerStruct->Thickness: "Thickness of the layer in meters above the base altitude. Always a positive value."
> 
> Is this unclear?

No not unclear. Just wondering if it would make sense perhaps to express the underwater layer differently. But it does not matter for the data interchange in any case. Keep as is.

**Pull request merged**
